apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: openshift-sandboxed-containers-operator
  labels:
    name: kata-monitor
spec:
  selector:
    name: kata-monitor
  ports:
    - name: metrics
      port: 8090
      protocol: TCP
