apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kata-monitor
  namespace: openshift-sandboxed-containers-operator
spec:
  namespaceSelector:
    matchNames:
    - openshift-sandboxed-containers-operator
  selector:
    matchLabels:
      name: kata-monitor
  endpoints:
  - port: metrics
